title: My blog
author: carlos10seg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My description of my blog 
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
